[theme]
base="dark"
primaryColor="#00ffcc"
backgroundColor="#0e1117"
secondaryBackgroundColor="#1a1c24"
textColor="#ffffff"
font="sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"
